modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mixins]]
config = "minecat_utils_fixes.xplat.mixins.json"

[[mixins]]
config = "minecat_utils_fixes.neoforge.mixins.json"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "Minecat Utils: Fixes"
authors = "Kneelawk"
description = "Fixes for the Minecat modpack."
logoFile = "assets/${mod_id}/icon.png"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "REQUIRED"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"
